# Generated by Django 5.2.6 on 2025-09-17 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('mat_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Study_Buddy.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('asn_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('past_due', models.BooleanField(default=False)),
                ('due_soon', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Study_Buddy.user')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
