# Generated by Django 5.2 on 2025-10-22 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Study_Buddy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="title",
            field=models.CharField(default="no title", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments_related_name",
                to="Study_Buddy.user",
            ),
        ),
        migrations.AlterField(
            model_name="materials",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials_related_name",
                to="Study_Buddy.user",
            ),
        ),
    ]
